baseurl: 'https://matrix-python.github.io/'
canonifyURLs: false
disableAliases: true
disableHugoGeneratorInject: true
enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
buildDrafts: true
languageCode: en-US
paginate: 7
rssLimit: 10
outputs:
  home:
    - HTML
    - RSS
    - REDIRECTS
    - HEADERS
  section:
    - HTML
    - RSS
    - SITEMAP
mediaTypes:
  text/netlify:
    suffixes:
      - ''
    delimiter: ''
outputFormats:
  REDIRECTS:
    mediaType: text/netlify
    baseName: _redirects
    isPlainText: true
    notAlternative: true
  HEADERS:
    mediaType: text/netlify
    baseName: _headers
    isPlainText: true
    notAlternative: true
  SITEMAP:
    mediaType: application/xml
    baseName: sitemap
    isHTML: false
    isPlainText: true
    noUgly: true
    rel: sitemap
caches:
  getjson:
    dir: ':cacheDir/:project'
    maxAge: 10s
markup:
  goldmark:
    extensions:
      linkify: false
    parser:
      autoHeadingID: true
      autoHeadingIDType: github
      attribute:
        block: true
        title: true
    renderer:
      unsafe: true
  highlight:
    codeFences: false
    guessSyntax: false
    hl_Lines: ''
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    style: dracula
    tabWidth: 4
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
permalinks:
  blog: '/blog/:year/:title/'
minify:
  tdewolff:
    html:
      keepWhitespace: false
module:
  hugoVersion:
    extended: true
    min: 0.80.0
    max: ''
  mounts:
    - source: node_modules/@hyas/doks/archetypes
      target: archetypes
    - source: node_modules/@hyas/doks/assets
      target: assets
    - source: node_modules/@hyas/doks/data
      target: data
    - source: node_modules/@hyas/doks/layouts
      target: layouts
    - source: node_modules/@hyas/doks/static
      target: static
    - source: node_modules/flexsearch
      target: assets/js/vendor/flexsearch
    - source: node_modules/katex
      target: assets/js/vendor/katex
    - source: assets
      target: assets
    - source: static
      target: static
    - source: content
      target: content
    - source: layouts
      target: layouts
    - source: archetypes
      target: archetypes
    - source: data
      target: data
    - source: node_modules/mermaid
      target: assets/mermaid
    - source: node_modules/@fortawesome/fontawesome-free/scss
      target: assets/scss/fontawesome
    - source: node_modules/@fortawesome/fontawesome-free/webfonts
      target: static/fonts/vendor/fontawesome
