[[main]]
  name = "Home"
  url = "/"
  weight = 10

[[main]]
  name = "Docs"
  url = "/docs/prologue/introduction/"
  weight = 20

[[main]]
  name = "Blog"
  url = "/blog/"
  weight = 30

[[main]]
  name = "About"
  url = "/about/"
  weight = 40

# [[main]]
#   name = "Code of Conduct"
#   url = "/docs/contributing/coc/"
#   weight = 40

[[docs]]
  name = "Prologue"
  weight = 10
  identifier = "prologue"
  url = "/docs/prologue/"

[[docs]]
  name = "Tutorial"
  weight = 20
  identifier = "tutorial"
  url = "/docs/tutorial/"

[[docs]]
  name = "Code of Conduct"
  weight = 30
  identifier = "code_of_conduct"
  url = "/docs/code_of_conduct/"

[[docs]]
  name = "Contibuting"
  weight = 40
  identifier = "contributing"
  url = "/docs/contributing/"

[[docs]]
  name = "Help"
  weight = 60
  identifier = "help"
  url = "/docs/help/"

[[internal]]
  name = "Documentaion"
  weight = 10
  identifier = "documentation"
  url = "/internal/documentation"

[[internal]]
  name = "Mjölnir"
  weight = 20
  identifier = "mjolnir"
  url = "/internal/mjolnir"

[[social]]
  name = "Matrix"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"-32 -27.2 64 54.3\" fill=\"currentColor\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M-30.6-25.9v51.8h3.7v1.2H-32v-54.3h5.2v1.2L-30.6-25.9z M-9.8-9.5v2.6h0.1c0.7-1,1.5-1.8,2.5-2.3S-5.1-10-3.8-10c1.2,0,2.3,0.2,3.4,0.7S1.4-8,1.9-6.8C2.5-7.6,3.2-8.4,4.2-9s2.2-1,3.5-1c1,0,2,0.1,2.8,0.4s1.6,0.6,2.2,1.2s1.1,1.3,1.5,2.2s0.5,2,0.5,3.2v13H9.5v-11L9.4-2.9C9.4-3.5,9.2-4,9-4.4s-0.6-0.8-1-1S7-5.8,6.2-5.8S4.9-5.7,4.4-5.4C4-5.1,3.6-4.7,3.3-4.3c-0.3,0.5-0.4,1-0.5,1.6S2.7-1.5,2.7-0.9V9.9h-5.3V-1l0-1.7c0-0.6-0.1-1.1-0.3-1.6s-0.5-0.9-0.9-1.1S-5-5.8-5.9-5.8c-0.2,0-0.6,0.1-1,0.2C-7.3-5.5-7.7-5.3-8.1-5c-0.4,0.3-0.7,0.8-1,1.4s-0.4,1.4-0.4,2.3V9.9h-5.3V-9.5L-9.8-9.5zM30.6,25.9v-51.8h-3.7v-1.2H32v54.3h-5.2v-1.2H30.6z\"></path></svg>"
  url = "https://matrix.to/#/#python-community:matrix.org"
  post = "v0.1.0"
  weight = 10

[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/matrix-python/"
  post = "v0.1.0"
  weight = 20

[[footer]]
  name = "Code of Conduct"
  url = "/docs/code_of_conduct/"
  weight = 10

[[footer]]
  name = "GDPR"
  url = "/privacy-policy/gdpr/"
  identifier = "GDPR"
  weight = 30

[[footer]]
  name = "Imprint"
  url = "/privacy-policy/imprint/"
  identifier = "Imprint"
  weight = 40
