title: Matrix+Python
titleSeparator: "-"
titleAddition: A Modern Python Chat
description: >-
  We are the Python community on matrix, a free and open network for secure,
  decentralized communication.

## Open Graph
images: []
ogLocale: en_US
domainTLD: matrix-python.github.io/
titleHome: Matrix+Python

## Twitter Cards
twitterSite: ""
twitterCreator: ""

## JSON-LD
# schemaType = "Person"
schemaType: Organization
schemaName: Matrix+Python
schemaAuthor: Michael Sasser
schemaAuthorTwitter: ""
schemaAuthorLinkedIn: ""
schemaAuthorGitHub: "https://github.com/matrix-python/"
schemaLocale: en-US
schemaLogo: ""
schemaLogoWidth: 512
schemaLogoHeight: 512
schemaImage: ""
schemaImageWidth: 1280
schemaImageHeight: 640
schemaTwitter: ""
schemaLinkedIn: ""
schemaGitHub: "https://github.com/matrix-python/"
schemaSection: blog

## Sitelinks Search Box
siteLinksSearchBox: false

## Chrome Browser
themeColor: "#fff"

# Images
quality: 85
bgColor: "#fff"
landscapePhotoWidths:
  - 1920
  - 900
  - 800
  - 700
  - 600
  - 500
portraitPhotoWidths:
  - 1200
  - 800
  - 700
  - 600
  - 500
lqipWidth: 20x
smallLimit: 300

# Footer
footer: >-
  Designed by the Python Community on Matrix<br />team with the help of our <a
  href="/contributors">contributors</a> ❤️.<br />Based on <a
  href="https://getdoks.org/" target="_blank" rel="license noopener">Doks</a>,
  built with <a href="https://gohugo.io/" target="_blank" rel="license
  noopener">Hugo</a>.<br />Code licensed <a
  href="https://github.com/matrix-python/matrix-python.github.io/blob/master/LICENSE.md"
  target="_blank" rel="license noopener">MIT</a>, docs <a
  href="https://github.com/matrix-python/matrix-python.github.io/blob/master/LICENSE_DOCS.md" target="_blank"
  rel="license noopener">CC BY 4.0</a>.
copyRight: "Code licensed MIT, docs CC BY 4.0."

# Alert
alert: false
alertDismissable: true
alertText: Coming soon &mdash; This website is under development.

# Edit Page
repoHost: GitHub
docsRepo: "https://github.com/matrix-python/matrix-python.github.io"
docsRepoBranch: master
docsRepoSubPath: ""
editPage: true
lastMod: false

# custom
showRss: true
matrix_room_data_url: "https://matrix.org"
users_room: "#python:matrix.org"

options:
  lazySizes: true
  clipBoard: true
  instantPage: true
  flexSearch: true
  darkMode: true
  bootStrapJs: true
  breadCrumb: true
  highLight: true
  kaTex: true
  multilingualMode: false
  docsVersioning: false
  fullWidth: true
  mediumZoom: true
  snow: true
  forceSnow: false  # Force Snow immediately.

menu:
  section:
    auto: false
    collapsibleSidebar: false
