# Meta Data for SEO

## Homepage
title = "Matrix+Python"
titleSeparator = "-"
titleAddition = "A Modern Python Chat"
description = "We are the Python community on matrix, a free and open network for secure, decentralized communication."

## Open Graph
images = []
ogLocale = "en_US"
domainTLD = "matrix-python.github.io/"
titleHome = "Matrix+Python"

## Twitter Cards
twitterSite = ""
twitterCreator = ""

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Matrix+Python"
schemaAuthor = "Michael Sasser"
schemaAuthorTwitter = ""
schemaAuthorLinkedIn = ""
schemaAuthorGitHub = "https://github.com/matrix-python/"
schemaLocale = "en-US"
schemaLogo = ""
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = ""
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = ""
schemaLinkedIn = ""
schemaGitHub = "https://github.com/matrix-python/"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Copyright &copy; 2021 Michael Sasser. All Rights Reserved.<br /> Built with <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://getdoks.org/\">Doks</a>"

# Feed
copyRight = "Copyright (c) 2021 Michael Sasser"

# Alert
alert = false
alertDismissable = true
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
alertText = ""

# Edit Page
docsRepo = "https://github.com/matrix-python/matrix-python.github.io"
editPage = true
docsRepoBranch = "master"
repoHost = "GitHub"

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = false
  darkMode = true
  bootStrapJs = true
  breadCrumb = true
  highLight = true
  kaTex = true
  collapsibleSidebar = false
  multilingualMode = false # Not yet functional
  docsVersioning = false # Not yet functional
