---
overrides:
  - files: "*.js"
    options:
      trailingComma: es5
      tabWidth: 4
      singleQuote: true
      semi: true
  - files: "*.scss"
    options:
      tabWidth: 2
      singleQuote: false
