---
blank_issues_enabled: true
contact_links:
  - name: "⁉️ Need help with the website? Ask on Matrix!"
    url: https://matrix.to/#/#python-meta:matrix.org
    about: Please ask and answer website specific questions in our Meta room on Matrix.
  - name: "⁉️ Need help with the website? Ask in the Discussions on GitHub!"
    url: https://github.com/matrix-python/matrix-python.github.io/discussions
    about: or in the the repos GitHub Discussions.
