[[footer]]
  name = "Contributors"
  url = "/contributors/"
  weight = 10

[[footer]]
  name = "Code of Conduct"
  url = "/docs/code_of_conduct/"
  weight = 20

[[footer]]
  name = "GDPR"
  url = "/privacy-policy/gdpr/"
  identifier = "GDPR"
  weight = 30

[[footer]]
  name = "Imprint"
  url = "/privacy-policy/imprint/"
  identifier = "Imprint"
  weight = 40

[[footer]]
  name = "Internal"
  url = "/internal/documentation/about/"
  weight = 50
